### PR TITLE
Custom and Default categories routes and data model modificacions

### PR DESCRIPTION
**Pull request by kc-leung**

### CODE REVIEW

**Review by coreyjjames — CHANGES_REQUESTED** [review]
Instead of using a foreign key reference for groupCustomMarkCategory can you use a subdocument

**Comment by kc-leung** [comment]
> 
> 
> Instead of using a foreign key reference for groupCustomMarkCategory can you use a subdocument

Will it affect the implemented logic? Also how different is it could you tell which example can I follow?

**Comment by coreyjjames** [comment]
You probably will need to change a few things. The Marks, group feed and group chat use subdocuments. You can look at them for reference.  The reason for subdocuments is so when the group is deleted all the content for it gets deleted.

**Comment by kc-leung** [comment]
> 
> 
> You probably will need to change a few things. The Marks, group feed and group chat use subdocuments. You can look at them for reference. The reason for subdocuments is so when the group is deleted all the content for it gets deleted.

Doesn't it look the same? lol I actually use them to create that schema.

const customCategory = require('./groupSubDocs/customMarkCategory'); it is calling this subdoc

**Comment by coreyjjames** [comment]
You didn't do sub documents you used a foreign key reference. 
This is what you did, which is a foreign key referance not a subdocument
groupCustomMarkCategory: {type: Schema.Types.ObjectId, ref: 'groupCustomCategory' },

**Comment by kc-leung** [comment]
> 
> 
> You didn't do sub documents you used a foreign key reference.
> This is what you did, which is a foreign key referance not a subdocument
> groupCustomMarkCategory: {type: Schema.Types.ObjectId, ref: 'groupCustomCategory' },

I think it will be easier for me to just add a delete logic for custom category into deleteGroupById

**Comment by coreyjjames** [comment]
That makes things kinda messy, but if you do that you have to do the following.

- Initialize the group Custom Category in the add group function.
- Inside the add group make sure to add the deletion of  group Custom Category into the catch for the try-catch
- Then update the deleteGroupById function
- test it allot

**Comment by kc-leung** [comment]
> 
> 
> That makes things kinda messy, but if you do that you have to do the following.
> 
>     * Initialize the group Custom Category in the add group function.
> 
>     * Inside the add group make sure to add the deletion of  group Custom Category into the catch for the try-catch
> 
>     * Then update the deleteGroupById function
> 
>     * test it allot

Thanks! it is already set up in the addGroup function I just need to update the deleteGroupById function

**Review by coreyjjames — APPROVED** [review]

**Pull request merged**
