### PR TITLE
Add Authentication to routes

### LINKED ISSUE #29: Add Authentication to routes
Use JSON web tokens to authenticate the connection to the server.

### PR DESCRIPTION
**Pull request by coreyjjames**
fix #29

### CODE REVIEW

**Review by kc-leung — APPROVED** [review]
nice work! why expires every hour? instead of a month or so?

**Comment by coreyjjames** [comment]
> nice work! why expires every hour? instead of a month or so?

Normally when you leave a website for more than an hour or so, it will ask you to log in again.

**Comment by kc-leung** [comment]
> 
> 
> > nice work! why expires every hour? instead of a month or so?
> 
> Normally when you leave a website for more than an hour or so, it will ask you to log in again.

I wouldn't like to log in over an over again if I am doing through the same device

**Comment by coreyjjames** [comment]
> > > nice work! why expires every hour? instead of a month or so?
> > 
> > 
> > Normally when you leave a website for more than an hour or so, it will ask you to log in again.
> 
> I wouldn't like to log in over an over again if I am doing through the same device

oh lol, I was thinking of a website. I'll just remove the expire for now and we can decide if we need one later.

**Pull request merged**
